import { Inter } from "next/font/google";
import "./globals.css";
import DetailMarquee from "./components/DetailMarquee";
import Header from "./components/Header";
import Footer from "./components/Footer";
// import CartProvider from "./context/CartContext";
import FormModal from "./components/FormModal";
import dynamic from "next/dynamic";
const CartProvider = dynamic(() => import("./context/CartContext"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });
export const viewport = {
  themeColor: "#04D585",
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <DetailMarquee />
          <Header />
          {children}
          <Footer />
          <FormModal />
        </CartProvider>
      </body>
    </html>
  );
}
